# Generated by Django 4.1.7 on 2023-03-13 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=30)),
                ('affiliation', models.IntegerField(blank=True, default=None, verbose_name='所属关系')),
                ('employee_phone', models.CharField(max_length=30, verbose_name='员工电话')),
                ('employee_position', models.CharField(max_length=100, verbose_name='职位名称')),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_phone', models.CharField(max_length=100)),
                ('order_region', models.CharField(max_length=100)),
                ('car_company', models.CharField(max_length=100)),
                ('cable_specification', models.CharField(max_length=100)),
                ('cable_length', models.IntegerField()),
                ('charge', models.IntegerField()),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('note', models.CharField(blank=True, default='', max_length=300)),
                ('update_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.employee')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
    ]
